language: python
sudo: false
cache:
  directories:
  - $HOME/.cache/pip
env:
- TOXENV=py27
- TOXENV=py33
- TOXENV=py34
- TOXENV=pypy
- TOXENV=pypy3
install:
- pip install tox
script:
- tox
after_success:
- coveralls